module.exports = {
  auth: require('./auth'),
  duplication: require('./duplication'),
  kakaologin: require('./kakaologin'),
  login: require('./login'),
  logout: require('./logout'),
  mailverify: require('./mailverify'),
  finduserinfo: require('./finduserinfo'),
  modify: require('./modify'),
  modifypw: require('./modifypw'),
  signup: require('./signup'),
  withdraw: require('./withdraw'),
  alertmail: require('./alertmail'),
  modifypw: require('./modifypw'),
  kakaowithdraw: require('./kakaowithdraw'),
};
