module.exports = {
  auth: require('./auth'),
  kakaologin: require('./kakaologin'),
  kakaoSignup: require('./kakaoSignup'),
  login: require('./login'),
  logout: require('./logout'),
  emailVerification: require('./emailVerification'),
  finduserinfo: require('./finduserinfo'),
  info: require('./info'),
  signup: require('./signup'),
  withdrawal: require('./withdrawal'),
  reservationNotice: require('./reservationNotice'),
  kakaoWithdrawal: require('./kakaoWithdrawal'),
  guest: require('./guest'),
};
